Scuffed manual parser
humleflue/P4 pull request #1
Opened 2021-03-04 13:53 UTC by humleflue

2021-03-10 12:30 UTC, christopher-jensen requested changes

2021-03-10 12:30 UTC, christopher-jensen commented on parser-by-hand/TokenStream.java
> +        return tokens.get(this.index);
Du peeker den nuværende token og ikke den næste. Skal være this.index + 1

2021-03-10 12:30 UTC, christopher-jensen commented on parser-by-hand/Main.java
> +	private static void Type() {
Generel kommentar/spørgsmål. Der er mange steder hvor du siger if(ts.peek == something){gør dette} else{gør dette}, men ser ikke noget sted at du smider en error hvis du ikke matcher. Altså hvis hverken den ene, anden, tredje eller nogen som helst if statement evaluerer til true, så går vi bare videre og får kun error fordi vi prøver at matche end of file ($). Altså får vi kun én fejl. Måske jeg tager fejl, men så skal jeg have det forklaret

2021-03-10 12:30 UTC, christopher-jensen commented on parser-by-hand/Main.java
> +}
Generel kommentar:
Funktioner kommer ikke i den rækkefølge de bliver kaldt i hvilket er forvirrende, men minor issue

2021-03-10 13:57 UTC, humleflue commented
Har fikset alt det vi har snakket om :)

2021-03-10 13:58 UTC, christopher-jensen approved these changes

2021-03-11 07:40 UTC, laurits-mumberg approved these changes
LGTM!

2021-03-11 07:42 UTC, merged