Parser and AST working
humleflue/P4 pull request #11
Opened 2021-03-29 07:14 UTC by christopher-jensen

2021-03-29 08:41 UTC, JacobToftgaardRasmussen reviewed
NotType property should be removed from all nodes

2021-03-29 08:41 UTC, JacobToftgaardRasmussen commented on AntlrB/.idea/.gitignore
> +/httpRequests/
Delete this

2021-03-29 08:41 UTC, JacobToftgaardRasmussen commented on AntlrB/src/B/B.g4
> +logexpr : left=logexpr2 op=LOGAND right=logexpr                               #logAnd
```suggestion
logexpr : left=logexpr2 op=LOGAND right=logexpr                               #logAndOp
```

2021-03-29 08:41 UTC, JacobToftgaardRasmussen commented on AntlrB/src/B/B.g4
> +expr : left=logexpr op=LOGOR right=expr                                       #logOr
```suggestion
expr : left=logexpr op=LOGOR right=expr                                       #logOrOp
```

2021-03-29 08:41 UTC, JacobToftgaardRasmussen commented on AntlrB/src/B/Nodes/Abstract/Code.java
> +}
Delete this file

2021-03-29 08:41 UTC, JacobToftgaardRasmussen commented on AntlrB/src/B/Nodes/Nodes/CodeFuncDef.java
> +public class CodeFuncDef extends Code {
```suggestion
package B.Nodes.Nodes;

import B.Nodes.Abstract.*;

public class CodeFuncDef extends Node {
```

2021-03-29 08:41 UTC, JacobToftgaardRasmussen commented on AntlrB/src/B/Nodes/Nodes/CodeStmt.java
> +public class CodeStmt extends Code {
```suggestion
package B.Nodes.Nodes;

import B.Nodes.Abstract.*;

public class CodeStmt extends Node {
```

2021-03-29 08:41 UTC, JacobToftgaardRasmussen commented on CUP-parser/AST/Nodes/Followterm.java
> +}
Delete this

2021-03-31 15:23 UTC, humleflue commented on AntlrB/.idea/.gitignore
> +/../../../../../../../:\Users\chris\4-semester\Projekt\AntlrB\.idea/dataSources/
This looks wrong...

2021-03-31 15:25 UTC, humleflue requested changes
Looks good over all!

I'd like the root folder's name to be renamed to something like ANTLR-AST instead of AntlrB.
Altso look at all the comments Jacob made as well as the one I made.

2021-04-02 08:15 UTC, humleflue approved these changes
LGTM!

2021-04-02 08:20 UTC, merged