The test changes have been put onto this branch which is a clone from master
humleflue/P4 pull request #53
Opened 2021-05-06 05:00 UTC by JacobToftgaardRasmussen

2021-05-06 07:50 UTC, christopher-jensen requested changes
Ser finno ud. Jeg har sat lidt kommentarer og spørgsmål. Når den er merget skal alle "bool" ændres til "boolean", "endf" til "end" og ENDF token i grammatikken skal ændres til END

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/Auxiliary/TestCase.java
> +
Var det ikke createTree vi ville beholde og så generateTree der skulle fjernes?

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/CodeGenerationVisitor/generatedCodeAndGivenCodeComparisonTests.java
> +    public void GeneratedCodeAndExpectedCodeTheSame_ShouldPass(String buffCode, String targetCode ) throws IOException {
Synes navnet er meget vagt. Hvis den tjekker alle cases i en kan vi eventuelt kalde den "CodeGenCheckAllProductions_ShouldPass

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/LexerAndParser/Data/expressionsTest.csv
> +endf
Så det passer med ny grammatik
```suggestion
end
```

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/LexerAndParser/Data/functionsTest.csv
>   endf
```suggestion
 end

```

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/LexerAndParser/Data/ifChainTests.csv
> +endf"
```suggestion
end"
```

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/LexerAndParser/Data/validDeclarationTests.csv
> +"bool test() = return true; end"
```suggestion
"boolean test() = return true; end"
```

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/LexerAndParser/LexerTests.java
> +    }
Jeg forstår ikke hvordan de her test gør noget. Hvor bliver der asserted?

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/LexerAndParser/ParserTests.java
> +            fail();
Vores funktion?

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/SymbolTable/SymbolTableTests.java
> +        ParseTree tree = createTree("number func() = return 1; endf");
```suggestion
        ParseTree tree = createTree("number func() = return 1; end");
```

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_FuncdefReturnTypeTests.java
> +        createTreeWithSymbols(String.format("%s f() = return %s; endf", type, expr));
```suggestion
        createTreeWithSymbols(String.format("%s f() = return %s; end", type, expr));
```

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_FuncdefReturnTypeTests.java
> +        createTreeWithSymbols(String.format("%s f() = return %s; endf", type, expr));
```suggestion
        createTreeWithSymbols(String.format("%s f() = return %s; end", type, expr));
```

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_IfSentenceTests.java
> +        createTreeWithSymbols(String.format("bool f() = if(%s) return true; return true; endf", trueOrFalse));
```suggestion
        createTreeWithSymbols(String.format("boolean f() = if(%s) return true; return true; end", trueOrFalse));
```

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_IfSentenceTests.java
> +        createTreeWithSymbols(String.format("bool f() = if(%s) return true; return true; endf", number));
```suggestion
        createTreeWithSymbols(String.format("boolean f() = if(%s) return true; return true; end", number));
```

2021-05-06 07:50 UTC, christopher-jensen commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_IfSentenceTests.java
>                  "bool f() = if(true %s true) return true; return true; endf", binaryBoolOperator));
```suggestion
                "boolean f() = if(true %s true) return true; return true; end", binaryBoolOperator));
```

2021-05-10 07:04 UTC, laurits-mumberg commented on ANTLR/test/tests/LexerAndParser/LexerTests.java
> +        System.out.println(errors);
glemt?

2021-05-10 07:11 UTC, laurits-mumberg commented on ANTLR/test/tests/LexerAndParser/ParserTests.java
> +    @CsvFileSource(resources = testPath + "invalidDeclarationTests.csv")
Vi tester vist bare lexeren igen her :trollface:

2021-05-10 07:12 UTC, laurits-mumberg commented on ANTLR/test/tests/LexerAndParser/ParserTests.java
> +            fail();
Nej, fail er ikke vores funktion Christoffer. Det er Junit

2021-05-10 07:13 UTC, laurits-mumberg commented on ANTLR/test/tests/LexerAndParser/ParserTests.java
> +            fail();
Men christoffer har ret. Måske brug AssertDoesNotThrow

2021-05-10 07:13 UTC, laurits-mumberg commented on ANTLR/test/tests/LexerAndParser/ParserTests.java
> +            fail();
🚎

2021-05-10 08:58 UTC, closed without merging