One line function
humleflue/P4 pull request #54
Opened 2021-05-06 12:45 UTC by laurits-mumberg

2021-05-10 07:09 UTC, humleflue requested changes
Love all the abstractions. I've suggested some small changes though.

2021-05-10 07:09 UTC, humleflue commented on ANTLR/src/Compiler/Buff.g4
> +funcDef : typeAndId LPAREN funcDefParams? RPAREN ASSIGN stmts* returnStmt END       #ifFunction
As an if-sentence isn't necessary in this production, I find the name wierd.

2021-05-10 07:09 UTC, humleflue commented on ANTLR/src/Compiler/Buff.g4
> +funcDef : typeAndId LPAREN funcDefParams? RPAREN ASSIGN stmts* returnStmt END       #ifFunction
Maybe call it multiLineFunction instead?

2021-05-10 07:09 UTC, humleflue commented on ANTLR/src/Compiler/CodeGeneration/JavaScriptCodeGenerationVisitor.java
> +        result += getStringFromTokenList(i -> visit(ctx.stmts(i)), 0, stmtsSize, " ");
Pretty sure this method is overloaded, so that you can reduce it to this:
```suggestion
        result += getStringFromTokenList(i -> visit(ctx.stmts(i)), stmtsSize);
```

2021-05-10 07:09 UTC, humleflue commented on ANTLR/src/Compiler/ContextualAnalysis/ReferenceCheckerListener.java
> +        currentScope = scopes.get(ctx);
Concider abstracting this statement into an auxiliary function, to reduce code replication. Then, if this statement changes, we will only have to change it in that function.

2021-05-10 07:09 UTC, humleflue commented on ANTLR/src/Compiler/SymbolTable/SymbolTableGeneratorListener.java
> +        } catch (Exception e){
```suggestion
        try { 
            currentScope.defineSymbol(symbol);
        } 
        catch (Exception e){
```

2021-05-10 07:09 UTC, humleflue commented on ANTLR/src/Compiler/SymbolTable/SymbolTableGeneratorListener.java
>          } catch (Exception e){
```suggestion
        try { 
            currentScope.defineSymbol(symbol);
        } 
        catch (Exception e){
```

2021-05-10 07:09 UTC, humleflue commented on ANTLR/src/Compiler/SymbolTable/SymbolTableGeneratorListener.java
>          currentScope = currentScope.getEnclosingScope();
Maybe abstract this statement away too.

2021-05-10 07:16 UTC, humleflue commented
Also, rewrite the tests, as the name of the production has changed.

2021-05-10 11:23 UTC, laurits-mumberg commented on ANTLR/src/Compiler/Buff.g4
> +funcDef : typeAndId LPAREN funcDefParams? RPAREN ASSIGN stmts* returnStmt END       #ifFunction
ok
![image](https://user-images.githubusercontent.com/15343686/117652024-f47b6080-b192-11eb-818e-9d6fbcd85157.png)

2021-05-10 11:31 UTC, laurits-mumberg commented on ANTLR/src/Compiler/CodeGeneration/JavaScriptCodeGenerationVisitor.java
> +        result += getStringFromTokenList(i -> visit(ctx.stmts(i)), 0, stmtsSize, " ");
Det var den ikke, så det lavede jeg

2021-05-10 11:32 UTC, laurits-mumberg commented on ANTLR/src/Compiler/SymbolTable/SymbolTableGeneratorListener.java
>          currentScope = currentScope.getEnclosingScope();
done

2021-05-10 12:54 UTC, JacobToftgaardRasmussen approved these changes, later dismissed
LRGILIALAYAB @laurits-mumberg

2021-05-10 12:57 UTC, JacobToftgaardRasmussen submitted a review, later dismissed
I guess this must be then end.

2021-05-11 10:57 UTC, humleflue submitted a review, later dismissed

2021-05-11 10:57 UTC, humleflue commented on ANTLR/src/Compiler/CodeGeneration/JavaScriptCodeGenerationVisitor.java
> +        result += visit(funcParams);
Maybe do null-check?

2021-05-11 10:57 UTC, humleflue commented on ANTLR/src/Compiler/ContextualAnalysis/TypeCheckerVisitor.java
> +        int returnType; // initialized to -1 to check if switchcase evaluated
```suggestion
        int returnType;
```

2021-05-11 10:57 UTC, humleflue commented on ANTLR/src/Compiler/ContextualAnalysis/TypeCheckerVisitor.java
> +    }
Remove this. It's more cryptic to use than just having the for-loop in the code.

2021-05-11 11:35 UTC, humleflue approved these changes
I ❤️ it.

2021-05-12 06:59 UTC, merged