Fix issue 43
humleflue/P4 pull request #55
Opened 2021-05-07 09:48 UTC by humleflue

2021-05-07 09:49 UTC, humleflue commented
Please do not delete the branch after merging.

2021-05-11 11:10 UTC, christopher-jensen approved these changes
Det ser super godt ud, jeg har sat en kommentar til refaktorering og en undren

2021-05-11 11:10 UTC, christopher-jensen commented on ANTLR/src/Compiler/ContextualAnalysis/TypeCheckerVisitor.java
>                  if (left != NUMTYPE || right != NUMTYPE)
Eventuelt lav sammenligning til et flag, da vi bruger den to steder.

2021-05-11 11:10 UTC, christopher-jensen commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_FuncdefReturnTypeTests.java
> +        ParseTreeVisitor<Integer> visitor = new TypeCheckerVisitor(symbolTable.globalScope, symbolTable.scopes, new MockErrorListener());
Meningen at der skal være 3 milliarder citationstegn?

2021-05-11 11:36 UTC, humleflue commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_FuncdefReturnTypeTests.java
> +        ParseTreeVisitor<Integer> visitor = new TypeCheckerVisitor(symbolTable.globalScope, symbolTable.scopes, new MockErrorListener());
Jep. Det er en block string i Java 👍 Alternativet ville være at konkatenere med '\n' og +.

2021-05-11 11:37 UTC, humleflue commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_FuncdefReturnTypeTests.java
> +        ParseTreeVisitor<Integer> visitor = new TypeCheckerVisitor(symbolTable.globalScope, symbolTable.scopes, new MockErrorListener());
Det ville skabe en del flere citationstegn i sidste ende 😅

2021-05-11 11:38 UTC, humleflue commented on ANTLR/src/Compiler/ContextualAnalysis/TypeCheckerVisitor.java
>                  if (left != NUMTYPE || right != NUMTYPE)
Det kunne man godt. Jeg synes det ville være lidt mærkeligt, da flaget ikke bruges i alle switchcases. Jeg prøvede også at abstrahere det væk i en funktion, men det blev også bare mindre læsbart imo.

Vi kan godt gøre det, hvis du synes. Let me know what you think.

2021-05-11 11:40 UTC, humleflue commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_FuncdefReturnTypeTests.java
> +        ParseTreeVisitor<Integer> visitor = new TypeCheckerVisitor(symbolTable.globalScope, symbolTable.scopes, new MockErrorListener());
```
                "number f() =\n" +
                    "if(true) return 2;\n" + ...
```

2021-05-11 12:43 UTC, christopher-jensen requested changes

2021-05-11 12:43 UTC, christopher-jensen commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_BooleanExpressionTests.java
> +}
Vi mangler vel en logicalNot Should pass

2021-05-11 12:43 UTC, christopher-jensen commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_IfSentenceTests.java
> +    public void EqualityComparisonInIfSentence_ShouldThrow(String operator) {
Omdøb så vi ved at der tale om number vs boolean

2021-05-11 12:43 UTC, christopher-jensen commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_NumberExpressionTests.java
> +    public void BooleanComparisonOperators_ShouldThrow(String operator) {
Ikke med på hvad denne test gør

2021-05-11 12:43 UTC, christopher-jensen commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_NumberExpressionTests.java
> +}
Jeg er ikke helt med på hvad det er vi tester her så den kan jeg ikke rette

2021-05-11 18:54 UTC, humleflue commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_BooleanExpressionTests.java
> +}
Jeg har skrevet forkert i navnet. Den skal jo passe 😅

2021-05-11 18:55 UTC, humleflue commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_BooleanExpressionTests.java
> +}
Godt spottet!

2021-05-11 19:01 UTC, humleflue commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_IfSentenceTests.java
> +    public void EqualityComparisonInIfSentence_ShouldThrow(String operator) {
Det bliver allerede testet i `BoolNumberComparisonInIfSentence_ShouldThrow()` på linje 79 i koden (bare i omvendt rækkefølge), så jeg sletter testen. Jeg har slettet en del tests fra filen, da de er dækket af de nye tests.

2021-05-11 19:05 UTC, humleflue commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_NumberExpressionTests.java
> +    public void BooleanComparisonOperators_ShouldThrow(String operator) {
Jeg kan godt se, at jeg fik navngivet expression-testene lidt mærkeligt isoleret set (de giver mening med klassenavnet i mente, når man kører testene), men jeg har omdøbt dem til, at de (forhåbentligt) også giver mening isoleret set.

2021-05-11 19:06 UTC, humleflue commented on ANTLR/test/tests/TypeCheckerVisitor/TypeChecker_NumberExpressionTests.java
> +}
Forhåbentligt giver det bedre mening med det nye navn!!

2021-05-12 06:59 UTC, christopher-jensen commented on ANTLR/src/Compiler/ContextualAnalysis/TypeCheckerVisitor.java
>                  if (left != NUMTYPE || right != NUMTYPE)
Det cool. Den er også læsbar nu

2021-05-12 07:03 UTC, christopher-jensen submitted a review, later dismissed

2021-05-12 07:11 UTC, christopher-jensen approved these changes

2021-05-12 07:11 UTC, merged