Symbol table tests
humleflue/P4 pull request #62
Opened 2021-05-12 10:31 UTC by laurits-mumberg

2021-05-12 11:04 UTC, humleflue requested changes
Lidt småkommentarer, ellers er det skide godt 👍

2021-05-12 11:04 UTC, humleflue commented on ANTLR/test/tests/SymbolTable/Data/functionParameterTest.csv
> +"number func(number x, boolean y) = 1;","x", "1"
Please add a header explaining what the different entries represent

2021-05-12 11:04 UTC, humleflue commented on ANTLR/test/tests/SymbolTable/Data/functionReturnTypeTest.csv
> +"number func() = return 1; end",1
Please add a header explaining what the different entries represent

2021-05-12 11:04 UTC, humleflue commented on ANTLR/test/tests/SymbolTable/SymbolTableTests.java
> +    }
Er det her ikke en type checker test?

2021-05-12 11:04 UTC, humleflue commented on ANTLR/test/tests/SymbolTable/SymbolTableTests.java
> +    public void GivenRetunType_ReturnsGivenType(String sourceCode, int type) {
Omdøb testen til et mere sigende navn

2021-05-12 11:04 UTC, humleflue commented on ANTLR/test/tests/SymbolTable/SymbolTableTests.java
> +        });
```suggestion
        Assertions.assertThrows(Exception.class, () -> getWalker(tree));
```

2021-05-12 11:04 UTC, humleflue commented on ANTLR/test/tests/SymbolTable/SymbolTableTests.java
> +        });
```suggestion
        Assertions.assertThrows(Exception.class, () -> getWalker(tree));
```

2021-05-13 06:34 UTC, laurits-mumberg commented on ANTLR/test/tests/SymbolTable/Data/functionParameterTest.csv
> +"number func(number x, boolean y) = 1;","x", "1"
Det er ikke noget vi har i andre tests, så ved ikke helt hvordan man gør det?

2021-05-13 06:34 UTC, laurits-mumberg commented on ANTLR/test/tests/SymbolTable/Data/functionReturnTypeTest.csv
> +"number func() = return 1; end",1
Sammen kommentar

2021-05-13 06:37 UTC, laurits-mumberg commented on ANTLR/test/tests/SymbolTable/SymbolTableTests.java
> +    }
Det vil jeg ikke sige. Den tjekker jo bare om symbol tablet gemmer rigtigt på types, hvilket er en af dens primære funktioner. Et andet argument imod er at typecheck visitoren aldrig bliver brugt.

2021-05-13 06:38 UTC, laurits-mumberg commented on ANTLR/test/tests/SymbolTable/SymbolTableTests.java
> +    public void GivenRetunType_ReturnsGivenType(String sourceCode, int type) {
done

2021-05-13 06:43 UTC, humleflue commented on ANTLR/test/tests/SymbolTable/Data/functionParameterTest.csv
> +"number func(number x, boolean y) = 1;","x", "1"
Se eksempel her: ANTLR\test\tests\CodeGenerationVisitor\Data\buffCodeAndTargetCode.csv

2021-05-13 06:43 UTC, humleflue commented on ANTLR/test/tests/SymbolTable/Data/functionReturnTypeTest.csv
> +"number func() = return 1; end",1
Se eksempel her: ANTLR\test\tests\CodeGenerationVisitor\Data\buffCodeAndTargetCode.csv

2021-05-13 06:44 UTC, laurits-mumberg commented on ANTLR/test/tests/SymbolTable/Data/functionParameterTest.csv
> +"number func(number x, boolean y) = 1;","x", "1"
done

2021-05-13 06:44 UTC, laurits-mumberg commented on ANTLR/test/tests/SymbolTable/Data/functionReturnTypeTest.csv
> +"number func() = return 1; end",1
done

2021-05-13 06:45 UTC, humleflue approved these changes

2021-05-13 06:49 UTC, merged